'use strict';
var config=require('config');
var moment=require("moment");
var log4js=require('log4js');
var timer=require('../lib/timer');
var bangoDB=require('../lib/bangodb');
var bangodb=new bangoDB();
var logger=log4js.getLogger();
logger.error({nihao:111});
// console.log(process.env);